"""Node execution handlers registry for Nexus.

Handlers execute work for AGENT, EXECUTOR, and VALIDATOR nodes.
HANDLERS DO NOT PERSIST ARTIFACTS TO THE DATABASE — they return ArtifactSpec instances
which the scheduler stamps and persists.
"""

from dataclasses import dataclass, field
from typing import Any

from app.models import Artifact, Node, NodeStatus, NodeType
from orchestrator.config import HandlerConfig


@dataclass
class ArtifactSpec:
    """Specification for an artifact generated by a handler."""
    kind: str
    filename: str
    content: str
    content_type: str = "text/plain"


@dataclass
class HandlerResult:
    """Result returned by a node handler."""
    status: NodeStatus
    artifacts: list[ArtifactSpec] = field(default_factory=list)
    logs: str = ""
    meta: dict[str, Any] = field(default_factory=dict)
